[profile.default]
src = 'contracts'
test = 'test/foundry'
out = 'out'
cache_path = 'cache_forge'
libs = ['lib']
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = 'cancun'
solc_version = '0.8.30'
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    'forge-std/=lib/forge-std/src/',
]

[invariant]
runs = 64
depth = 32
fail_on_revert = false
